#!/bin/bash

checkExitCode() {
if [ $? -ne 0 ]; then
	echo "Error"
	exit 1;
fi
}

BASEDIR=`dirname $0`

if [ $# -lt 1 ]; then echo "Error No inputs provided" && exit 1; fi

. $BASEDIR/io.sh 1 0 1 "$@"

echo $BCFTOOLS13_HOME/bcftools call -vmO v -o $OUTPUTS1 $INPUTS1
$BCFTOOLS13_HOME/bcftools call -vmO v -o $OUTPUTS1 $INPUTS1
checkExitCode
