#!/bin/bash

checkExitCode() {
if [ $? -ne 0 ]; then
	echo "Error"
	exit 1;
fi
}

BASEDIR=`dirname $0`

if [ $# -lt 1 ]; then echo "Error No inputs provided" && exit 1; fi

. $BASEDIR/io.sh 2 3 1 "$@"

echo $SAMTOOLS13_HOME/samtools mpileup -f $INPUTS2 -v -u -q $PARAMS1 -m $PARAMS2 -Q $PARAMS3 -o $OUTPUTS1 $INPUTS1
$SAMTOOLS13_HOME/samtools mpileup -f $INPUTS2 -v -u -q $PARAMS1 -m $PARAMS2 -Q $PARAMS3 -o $OUTPUTS1 $INPUTS1

checkExitCode
